async function main() {
  // TODO: Add something to verify if necessary
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
